Cadastro login
plane-it/site-institucional pull request #4
Opened 2023-08-22 13:01 UTC by danmrqs

avaliem se os atos derradeiros que foram feitos por minha pessoa estão corretos.

2023-08-22 13:16 UTC, Rafaqwert commented on Site/site/public/CSS/cadastro.css
Depois, coloca a fonte Oxanium para textos maiores e a fonte Ubuntu nos textos percorridos (se houver). Padrão do projeto.

2023-08-22 13:20 UTC, Rafaqwert commented on Site/site/public/CSS/login.css
Depois, coloca a fonte Oxanium para textos maiores e a fonte Ubuntu nos textos percorridos (se houver). Padrão do projeto.

2023-08-22 13:24 UTC, PereiraGus commented
Colocar máscara nos campos de CNPJ e telefone.
Avisar qual campo está dando problema também no texto do alerta, além das regras de formatação da senha.
Criar usuário no banco através do SQL para ser utilizado no código.

2023-08-22 13:24 UTC, PereiraGus commented
Colocar máscara nos campos de CNPJ e telefone.
Avisar qual campo está dando problema também no texto do alerta, além das regras de formatação da senha.
Criar usuário no banco através do SQL para ser utilizado no código.

2023-08-22 13:30 UTC, PereiraGus requested changes
Deixar mais claro no front de quem são as informações: da empresa//primeiro colaborador

Validar os campos de acordo com os tamanhos do banco de dados (ex: telefone).
Colocar máscara automática nos campos de CNPJ e telefone.
Avisar qual campo está dando problema também no texto do alerta, além das regras de formatação da senha caso esta esteja errada.
Quando der erro na inserção, avisar usuário.
Criar usuário no banco através do SQL para ser utilizado no código.

2023-08-22 13:39 UTC, Rafaqwert requested changes
Se atentar as fontes padronizadas para o projeto (Oxanium e Ubuntu);
Eliminar ambiguidade no cadastro (especificar se é empresa ou funcionário);
Corrigir validação do telefone;

2023-09-11 14:02 UTC, Rafaqwert approved these changes
Aprovado.

2023-09-11 14:12 UTC, PereiraGus requested changes
Separar cadastro da empresa e do funcionário e adicionar informações faltantes de acordo com o DER.
Acordado em reunião, 11/09, 11:12.

2023-09-11 18:04 UTC, PereiraGus approved these changes

2023-09-11 18:16 UTC, PereiraGus requested changes
- Trocar o banco mockado pelo [banco aprovado](https://bandteccom.sharepoint.com/:u:/s/Plane-it/ESVIJMARboRNoPImmRoXXq4BGM5YHuCK5LyjsrbaTxZKLw?e=jkpev9);
- Validações de tamanho de acordo com os campos do banco;
- Alerta da senha com mensagem pedindo o padrão correto;
- Reformular título do alerta (tirar "Xi...");
- Login ainda pede o CNPJ;
- Empresa não tem email, colaborador sim.

2023-09-12 12:35 UTC, gba-exe approved these changes
Resolvi os conflitos atuais.

2023-09-12 12:55 UTC, merged